print("This is the Split bill calculator")
totalBill = float(input("What is the total bill you have recieved "))
percentage_tip = int(input("What is the % of tip you're going to give "))
Total_num_of_ppl = int(input("How much people are splitting the bill"))
print("\n")
payment_for_each_member = ("%.2f" % round(float(((percentage_tip / 100 +1) * totalBill) / Total_num_of_ppl), 2))
tip_amount = "%.2f" % float(percentage_tip / 100 * totalBill)
print(f"Tip amount: Rs:{tip_amount}")
totalBill_float = float(totalBill)
tip_amount_float = float(tip_amount)
tip_and_total = (totalBill_float+tip_amount_float)
print(f"Total bill with tips: Rs:{tip_and_total}")
print(f"Each person have to pay: Rs: {payment_for_each_member}")