print("This is the Split bill calculator")
totalBill = float(input("What is the total bill you have recieved "))
percentagetip = int(input("What is the % of tip you're going to give "))
Totalnumofppl = int(input("How much people are splitting the bill"))
print("\n")
paymentforeachmember = ("%.2f" % round(float(((percentagetip / 100 +1) * totalBill) / Totalnumofppl), 2))
tipamount = "%.2f" % float(percentagetip / 100 * totalBill)
print(f"Tip amount: Rs:{tipamount}")
totalBill_float = float(totalBill)
tipamount_float = float(tipamount)
tipandtotal = (totalBill_float+tipamount_float)
print(f"Total bill with tips: Rs:{tipandtotal}")
print(f"Each person have to pay: Rs: {paymentforeachmember}")